### ISSUE TITLE
Jenkins X install instructions need to cover the fact that repositories are created private

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx-docs#1964]
Changes to the docs are needed due to the fact that repositories are not created private per default - see https://github.com/jenkins-x/jx/issues/5186

The docs should include something along these lines:

> Jenkins X creates  repositories per default as private.  This can cause issues when evaluating Jenkins X with GitHub using a free GitHub organisation to hold the various created (environment) repositories. For evaluation purposes you can use a GitHub user as owner of the repositories. Alternatively, you can enable public environment repositories by specifying the --git-public option as part of jx create or jx install"

Needs to mention also `environmentGitPublic` in the case of `jx boot`. 

Might need to get into a bit more detail for the using GitHub user case. Maybe its worth explicitly mentioning that GitHub allows free users to create private repositories, but not free organization (free as in no paid subscription)

**Comment by dennisnewel** [comment]
i added the following notice to https://jenkins-x.io/docs/getting-started/setup/boot/ since that is now the main "install jx" page.

<img width="938" alt="Screen Shot 2019-09-26 at 12 26 15 PM" src="https://user-images.githubusercontent.com/962391/65718729-03161200-e059-11e9-839a-b8b4ea3148a8.png">

let me know what you think @hferentschik  (will push a PR shortly)
