### ISSUE TITLE
Top hit for search term 'Boot' is in the labs docs 

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx-docs#2671]
Top hit for search term 'Boot' is https://jenkins-x.io/docs/labs/boot/ and https://jenkins-x.io/docs/labs/boot/getting-started/run/ opposed to https://jenkins-x.io/docs/getting-started/setup/boot/

**Comment by hferentschik** [comment]
I think this might be related to the fact that the 'Run Boot' page is also not available anymore from the left side navigation.

**Comment by vfarcic** [comment]
We need to put the notice from https://jenkins-x.io/docs/labs/ to all labs-related pages. Otherwise, if people get to them through Google search, instead of navigating through docs menus, they will think that all the experiments are valid ways to use JX, and that they are an integral part of it, instead of being closed (for now).

**Comment by ethangj** [comment]
Agreed, need to add the labs warning huge everywhere that mentions labs. @vfarcic do you want to add it here?

**Comment by vfarcic** [comment]
Done in https://github.com/jenkins-x/jx-docs/pull/2717 @ethangj. Who wants the honor or reviewing and approving it?

**Comment by ethangj** [comment]
Has to be @hferentschik , my approvals don't help.
