### ISSUE TITLE
Setup content under "Getting Started" is not reachable anymore  from left navigation

### ISSUE THREAD

**Issue by hferentschik** [jenkins-x/jx-docs#2672]
It seems the whole subtree of "Setup" is not reachable anymore from the current "Getting Started" menu. This includes cluster setup documentation as well as Boot documentation.

**Comment by hferentschik** [comment]
<img width="1127" alt="Screenshot 2020-04-28 at 10 01 36" src="https://user-images.githubusercontent.com/296354/80462627-44480a80-8937-11ea-9ca2-b9754259611d.png">

Nothing selected in the left-side menu for this page

**Comment by ethangj** [comment]
@sharepointoscar this seems like a major issue

**Comment by sharepointoscar** [comment]
This was by design. The idea is that the **Getting Started** guides the user through this.  Those pages still exist and folks who have bookmarked them will still get to them.  But our goal for the sure is to go through the **Getting Started** section and should have enough information - granted I have links to setup within the instructions if users need more detail.

The idea is not to overwhelm users in getting started but yet make the details available, which I have.

I think we need to take a step back and simply sketch the left nav instead of thinking there are *Issues* with the work being done, and have a plan that people see so as to avoid confusion.

@rawlingsj brought this up on our call earlier this week, there needs to be a User Experience design (UX).  

However, this first pass was quick and we did not **all** talk about what the plan was, I just did it, hence your confusion thinking this is an Issue @hferentschik 

Before I personally do any more work on this, I think we need to do basic UX and sketching out the navs.  

Thanks.;

/cc @ethangj

**Comment by ethangj** [comment]
I think the issue is we can't confuse a good getting started guide, which you're describing, with documentation. 

The docs pages themselves have to be there, the getting started guider is separate from the individual docs articles and doesn't replace them.

**Comment by hferentschik** [comment]
> This was by design. The idea is that the Getting Started guides the user through this. Those pages still exist and folks who have bookmarked them will still get to them

The issue is then that we are hiding some of the most valuable pages we have. We literally have no other page around Boot. Also, the full documentation (opposed to the quickstart) for the cluster creation lives there. We cannot have this disappear. If we don't want to have it under "Getting Started" we need to move them. 

Also breaking the expected navigation behaviour seems to be a bad thing. Even if I get to the content by bookmark or internal reference, you are then lost on where you are, since navigation context is not there.

**Comment by ethangj** [comment]
I would agree with @hferentschik , this is a rather urgent removal to correct. It can't be either/or with a getting started guide vs individual docs articles - need both.

@sharepointoscar i know you hate it but can you do a PR to restore those to the nav, separate from the getting started guide? we will keep iterating, but in the interim that info needs to be accessible.

**Comment by hferentschik** [comment]
Maybe the pages can move somewhere under "Reference"?

**Comment by sharepointoscar** [comment]
> Maybe the pages can move somewhere under "Reference"?

@hferentschik I think the Getting Started section has links to the Setup, so let me just try and surface it within that existing location to no break links...
