### ISSUE TITLE
Additional search box in left nav is superfluous and does not work

### ISSUE THREAD

**Issue by MarckK** [jenkins-x/jx-docs#3072]
**This is a Bug Report**

**Problem:**
In addition to the search box in the top nav, which works well, we have a search box in the left navigation column. This additional search box is superfluous and does not work at all. It has zero functionality. 

**Proposed Solution:**
We should remove the search box in the left navigation column.

**Page to Update:**
The left navigation column. For example, it can be seen here:
https://jenkins-x.io/docs/....

**Screen shot of left navigation column. The not-working, superfluous search box is at the top:**
<img width="220" alt="Screenshot 2020-09-22 at 09 26 08" src="https://user-images.githubusercontent.com/15032115/93859958-3c0db480-fcb6-11ea-8eb0-d959a5cf0e02.png">

**Comment by Haniket** [comment]
hi there,I am new to opensource and looking for Hacktoberfest........can I work on it

**Comment by salonigoyal2309** [comment]
@MarckK I would love to work on this issue :)

**Comment by MarckK** [comment]
Welcome! Our instructions for contributing to Jenkins X documentation site can be found here: 
https://jenkins-x.io/community/documentation/

**Comment by Haniket** [comment]
@MarckK thanks.....

**Comment by Haniket** [comment]
@MarckK  make server  command is not working to run server at localhost  localhost:1313..........plz help......

**Comment by ankitm123** [comment]
You should be using docker-compose, it's the preferred way to for development.
https://jenkins-x.io/community/documentation/#docker-compose-method

**Comment by Haniket** [comment]
@MarckK I had fixed the issue in my local environment but the issue is in "docsy" which is linked to another repository.....how to fix that.
thanks..

**Comment by ankitm123** [comment]
> @MarckK I had fixed the issue in my local environment but the issue is in "docsy" which is linked to another repository.....how to fix that.

So, docsy is added as a submodule in jx-docs repo. So, if the issue is in docsy, then you need to open an issue in docsy, fix it there and then update the submodule for jx-docs, by executing the following command from the root directory of jx-docs:
```
git submodule update --init --recursive --depth 1
```

Also, would you mind talking about the issue here, before moving to docsy. I took a prelim/rough look at the problem, and thought the issue was with docsy, however I don't think so anymore. I did create and close an [issue](https://github.com/google/docsy/issues/341) in docsy. May be I am missing some information :thinking: 

> and one thing more how can I assign this issue to myself...I think only you can do this....

Just type `/assign` as a comment in this issue.

**Comment by Haniket** [comment]
> Also, would you mind talking about the issue here, before moving to docsy. I took a prelim/rough look at the problem, and thought the issue was with docsy, however I don't think so anymore. I did create and close an [issue](https://github.com/google/docsy/issues/341) in docsy. May be I am missing some information 🤔


@ankitm123 as mentioned above that I have to remove the the left search bar from the navigation column because that search bar has no use there..............
   so the left column has path
                jx-docs\themes\docsy\layouts\partials\sidebar-tree.html

 and the above task I have to remove form part  of code from sidebar-tree.html 

and after removing this code the search bar is removed and the problem is resolved..............

am I doing any mistake......please help

thanks

**Comment by borntorock** [comment]
@Haniket deleting the `sidebar-tree.html` file might fix this issue but I don't think deleting the file in docsy module is appropriate. 

There's an example of [Kubeflow documentation](https://www.kubeflow.org/docs/) which does not have search bar on the left column side. The source code of Kubeflow docs is present [here](https://github.com/kubeflow/website). 

Now, you would have the see the changes present in the `sidebar-tree.html` file in the Kubeflow docs and the original sidebar-tree.html file in the docsy module as well as the any variable set in config.toml file (if any). 

For this issue, you can create a new file named `partials/sidebar-tree.html` in jx-docs repo and include the working changes here. This might help in some way.

**Comment by ankitm123** [comment]
@Haniket as @borntorock mentioned, removing things from docsy is not the right solution.
https://github.com/jenkins-x/jx-docs/blob/master/config.toml#L139 -> Since this is set to true, it should not be shown. Looking at the docsy codebase, the styling for the left search bar comes from https://github.com/google/docsy/blob/master/assets/scss/_sidebar-tree.scss#L138-L144 and the source code comes from here: https://github.com/google/docsy/blob/master/layouts/partials/sidebar-tree.html#L10-L19

The fastest way to fix this would be to include https://github.com/google/docsy/blob/master/assets/scss/_sidebar-tree.scss file here: https://github.com/jenkins-x/jx-docs/blob/master/assets/scss/_sidebar-tree.scss

However, this is a hack, and I think changing stylesheets this way, is not a scalable way of fixing this issue (So, if tomorrow the main scss file changes in docsy, we have to change it again here, which hardly makes any sense).

**Comment by borntorock** [comment]
> However, this is a hack, and I think changing stylesheets this way, is not a scalable way of fixing this issue 

I think the other way to fix this would be to simply create a new file named `partials/sidebar-tree.html` in jx-docs and remove these lines https://github.com/google/docsy/blob/master/layouts/partials/sidebar-tree.html#L10-L19

This way the content-desktop and content-mobile div blocks would be rendered as mentioned in the scss.

**Comment by Haniket** [comment]
> This way the content-desktop and content-mobile div blocks would be rendered as mentioned in the scss.
 
I also think so because almost same thing is given in the Kubeflow docs as mentioned above

**Comment by ankitm123** [comment]
Kubeflow uses an old version of docsy afaik. I don't think modifying similar things from docsy in our site is an approach I prefer, cuz when they make changes upstream we have to edit downstream, which is just extra work. I will look into it a bit more, if this is the only way to make it work, sounds very hacky to me.

**Comment by Haniket** [comment]
@ankitm have you find any because I am unable to find one......

**Comment by ankitm123** [comment]
It would be good to check the docsy docs and the example site.

**Comment by ankitm123** [comment]
@Haniket any updates? I am going to take a look at the docsy site tonight, and see if I can find some examples for you. If not, then I think we can go forward with doing it the way kubeflow is addressing it.

**Comment by Haniket** [comment]
ok @ankitm123

**Comment by ankitm123** [comment]
@Haniket I think this section from docsy has good information abt this issue: https://www.docsy.dev/docs/adding-content/lookandfeel/

As mentioned here, the issue is that we over-ride everything, and hence it does not hide the leftnav.

Would be good to just remove the offending scss (some details are here: https://github.com/jenkins-x/jx-docs/issues/3072#issuecomment-699650608) from here: https://github.com/jenkins-x/jx-docs/blob/master/assets/scss/_sidebar-tree.scss.

I would be interested to know what would happen if we remove All the files under assets/scss and only make relevant changes in `assets/scss/_variables_project.scss`, which seems to be the recommended way in hugo.

Let me know how it goes.

**Comment by ankitm123** [comment]
/unassign @Haniket 
@Haniket haven't heard back in some time, so going to take a crack at it.

**Comment by amino19** [comment]
@ankitm123 : Is the work done?

**Comment by ankitm123** [comment]
Yes, this can be closed. This was done already.
