### ISSUE TITLE
Add detailed configuration requriements for k3s

### ISSUE THREAD

**Issue by faisalthaheem** [jenkins-x/jx-docs#3499]
**This is a Feature Request**

**What would you like to be added**
Specify in the documents that when setting up with k3s the following environment variables should be defined
KUBERNETES_SERVICE_HOST=127.0.0.1
KUBERNETES_SERVICE_PORT=6443

**Why is this needed**
No instruction is given how to configure jx to use a custom k3s endpoint when running step "jx admin operator" command and it just fails saying it's unable to connect to k3s.

**Comments**
A completed .bashrc containing all the required variables when setting up k3s would be extremely useful and cut down on wasted time figuring out a lot of things.

**Comment by ankitm123** [comment]
Is kubectl able to connect to custom k3s endpoint without those env variables, but jx is not (is `kubectl get nodes` working?)? If yes, then it should be added.
Also, I think it might be better to link the relevant k3s docs, so that the end users can verify if they can connect to the cluster or not,  wdyt?

Few other thing that are missing in the docs include, when to use ngrok for example. 
You wont need it, if you are running on an EC2 instance that has a public IP attached to it.

K3s was added to the list as a local evaluation tool for new users to try out Jenkins X without incurring cloud costs, very excited to see that there is interest in k3s (https://ankit-mohapatra.netlify.app/JenkinsX/jx3-with-k3s/). 
Are u using Civo by any chance?

If you want to open a PR for this, I would be happy to review as well :)

**Comment by babadofar** [comment]
I don't think this issue applies anymore, k3s is used by several people and not seeing this issue reported.
