### ISSUE TITLE
"What is Jenkins X" page does not answer the question when one does not know what it is nor the purpose for Jenkins X

### ISSUE THREAD

**Issue by wblair-ebsco** [jenkins-x/jx-docs#3686]
While searching for info on how best to have Jenkins master determine the AWS regions in which is is running and to make that available to all pipelines and standalone jobs, I stumbled upon this page.

This page assumes one know something about Jenkins X and I don't so I can't take the time to consider using this as an alternative to traditional Jenkins.  I also cannot determine at a glance what is the relationship with traditional Jenkins and Jenkins X (if any).

If no relationship or functional compatibility to traditional Jenkins why are you calling this "Jenkins X" and causing confusion or ambiguity I do not have the time to research?

I'm interested in what you offer but do not have the time to figure out who or what you are and your motivations to be associated to traditional CloudBees "Jenkins".

**Comment by tomhobson** [comment]
Hey @wblair-ebsco, Jenkins X was a project created by CloudBees to replace Jenkins. However they've since pulled funding for the project so it's moved to a community driven project.

We've considered renaming the project a bunch of times, but it is going to take a lot of work to do this. Apologies for the confusion, this is a problem that we've had for a long time.

Closing this issue as I believe I've answered this question. Feel free to reopen if you feel I haven't.
